version: 2.1
orbs:
  sym: sym/sym@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      - approval/request:
          flow_srn: "e2e-testing:flow:approval_orb_strategy:latest"
          flow_inputs: '{
            "build_url": "${CIRCLE_BUILD_URL}",
            "workflow_id": "${CIRCLE_WORKFLOW_ID}",
            "duration": 300,
            "target_srn": "e2e-testing:access_target:custom:approval_orb_strategy-target:latest"
          }'
          request_slug: "request-test"
          sym_api_url: "https://api.staging.symops.com/api/v1"
          filters: *filters
      - wait_for_auto_approve:
          type: approval
          requires:
            - approval/request
      - approval/deescalate:
          request_slug: "request-test"
          sym_api_url: "https://api.staging.symops.com/api/v1"
          requires:
            - wait_for_auto_approve
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: sym/approval
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - approval/deescalate
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
